### ISSUE TITLE
Meta: ES Next

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent#1443]
Let's convert all WebTorrent packages to ES6. (Continued from https://github.com/webtorrent/webtorrent/issues/444)

Note that this is a separate task from async-await (Promises) support.

- [x] webtorrent
- [x] bittorrent-dht
- [x] bittorrent-peerid
- [x] bittorrent-protocol
- [x] bittorrent-tracker
- [x] create-torrent
- [x] magnet-uri
- [x] parse-torrent
- [x] render-media
- [x] torrent-discovery
- [x] ut_metadata
- [x] ut_pex
- [x] webtorrent-fixtures
- [x] addr-to-ip-port
- [x] webtorrent-cli
- [x] webtorrent-hybrid
- [x] load-ip-set
- [x] ip-set

**Comment by hgghyxo** [comment]
Do you plan to add support for ESModule like imports? 

```javascript
import { WebTorrent } from 'https://unpkg.com/webtorrent'
```

>Uncaught SyntaxError: The requested module 'https://unpkg.com/webtorrent' does not provide an export named 'WebTorrent'

**Comment by DiegoRBaquero** [comment]
@hgghyxo I think you have to do `import * as WebTorrent from ...`

**Comment by DiegoRBaquero** [comment]
Are you using webpack, babel?

**Comment by hgghyxo** [comment]
neither, ESModule: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import
the `<script type="module" src="...">` thingy

**Comment by DiegoRBaquero** [comment]
oh, then just use the normal import and it'll be available as a global.

There's no plan on supporting ES Modules atm

**Comment by hgghyxo** [comment]
Webtorrent-hybrid was't a big project: https://github.com/webtorrent/webtorrent-hybrid/pull/86  
:)

**Comment by jimmywarting** [comment]
PR's waiting to be merged

- [x] webtorrent
- [ ] bittorrent-dht
- [x] bittorrent-peerid
- [x] bittorrent-protocol
- [ ] bittorrent-tracker [#295](https://github.com/webtorrent/bittorrent-tracker/pull/295), [#296](https://github.com/webtorrent/bittorrent-tracker/pull/296), [#297](https://github.com/webtorrent/bittorrent-tracker/pull/297)
- [x] create-torrent
- [x] magnet-uri
- [x] parse-torrent
- [ ] render-media [#51](https://github.com/feross/render-media/pull/51)
- [x] torrent-discovery
- [x] ut_metadata
- [ ] ut_pex [23](https://github.com/webtorrent/ut_pex/pull/23)
- [x] webtorrent-fixtures
- [x] addr-to-ip-port
- [ ] webtorrent-cli [#82](https://github.com/webtorrent/webtorrent-cli/pull/82)
- [ ] webtorrent-hybrid [#87](https://github.com/webtorrent/webtorrent-hybrid/pull/87)
- [x] load-ip-set
- [ ] ip-set

**Comment by jimmywarting** [comment]
Not sure if it was intended to close this

**Comment by DiegoRBaquero** [comment]
Correct

**Comment by feross** [comment]
I just updated `render-media` to ES6 and pinged @transitive-bullshit for access to `ip-set` so we can merge this PR https://github.com/transitive-bullshit/ip-set/pull/7.

**Comment by feross** [comment]
Amazing – this issue is finally finished up :)

Thanks @transitive-bullshit for pushing out 2.0.0 of `ip-set`. I also just did some other maintenance tasks on that package and put out 2.0.1.

✨
