### ISSUE TITLE
Switch to ESM

### ISSUE THREAD

**Issue by DiegoRBaquero** [webtorrent/webtorrent#2177]
- [x] addr-to-ip-port
  - https://github.com/webtorrent/addr-to-ip-port/pull/21
- [x] bep53-range
  - https://github.com/webtorrent/bep53-range/pull/17
- [x] bittorrent-dht
  - https://github.com/webtorrent/bittorrent-dht/pull/248
- [x] bittorrent-peerid
  - https://github.com/webtorrent/bittorrent-peerid/pull/39
- [x] bittorrent-protocol
- [x] bittorrent-tracker
  - https://github.com/webtorrent/bittorrent-tracker/pull/431
- [x] bittorrent-lsd
  - https://github.com/webtorrent/bittorrent-lsd/pull/30
- [x] create-torrent
  - https://github.com/webtorrent/create-torrent/pull/187
- [x] fs-chunk-store
  - https://github.com/webtorrent/fs-chunk-store/pull/44
- [ ] instant.io
- [ ] ip-set
- [x] load-ip-set
  - https://github.com/webtorrent/load-ip-set/pull/37
- [x] lt_donthave
  - https://github.com/webtorrent/lt_donthave/pull/15
- [x] magnet-uri
  - https://github.com/webtorrent/magnet-uri/pull/60
- [x] node-bencode
  - https://github.com/webtorrent/node-bencode/pull/131
- [x] parse-torrent
  - https://github.com/webtorrent/parse-torrent/pull/118

~~- [ ] render-media~~
- [x] string2compact
  - https://github.com/webtorrent/string2compact/pull/33
- [x] torrent-discovery
  - https://github.com/webtorrent/torrent-discovery/pull/87
- [x] torrent-piece
  - https://github.com/webtorrent/torrent-piece/pull/32
- [x] ut_metadata
  - https://github.com/webtorrent/ut_metadata/pull/80
- [x] ut_pex
  - https://github.com/webtorrent/ut_pex/pull/57
- [x] webtorrent
- [x] webtorrent-cli
- [ ] webtorrent-desktop
- [x] webtorrent-fixtures
  - https://github.com/webtorrent/webtorrent-fixtures/pull/20
- [x] webtorrent-hybrid
- [ ] webtorrent.io

**Comment by ThaUnknown** [comment]
https://github.com/substack/tape/pull/547 was merged, so you should be able to keep tape, we'd need to update https://github.com/webtorrent/webtorrent/pull/2096

**Comment by DiegoRBaquero** [comment]
Awesome!

We need to update top-down, as ESM can support commonjs but not the other way around

**Comment by DiegoRBaquero** [comment]
@king-11 all low level package are missing so feel free to refactor them

**Comment by king-11** [comment]
thanks @DiegoRBaquero working on `bittorrent-protocol` right now

**Comment by king-11** [comment]
Working on test I had to change the test command to `standard && tape test/*.mjs` even though all extensions are still `.js` otherwise tape was throwing errors

**Comment by king-11** [comment]
@DiegoRBaquero I have created 3 new PRs and updated the dht one can you PTAL

**Comment by king-11** [comment]
🎉🎉
