### ISSUE TITLE
WebTorrent v1.0.0

### ISSUE THREAD

**Issue by feross** [webtorrent/webtorrent#668]
Here's what I think WebTorrent needs to be v1.0.0.
- [ ] Published spec for the WebTorrent protocol (BEP) #168
  - This is currently preventing adoption by other clients
- [x] CPU leak is causing Instant.io and WebTorrent.app to lag the kernel after ~10 minutes #551
  - This currently preventing real-world, long-term usage of WebTorrent
- [x] Release simple desktop application
  - This is currently preventing users from easily seeding torrents over the long-term
  - This is currently preventing web peers from having lots of potential peers

**Comment by wI2L** [comment]
Looking forward for the WebTorrent protocol BEP.

**Comment by dcposch** [comment]
Some more WebTorrent 1.0 ideas:

- [ ] TrackerSocket refactor. Might fix #922 
- [ ] Enforce max numbers of WebRTC peers, BitTorrent peers, and web seeds allowed at a time. I think this will help performance when torrenting many files at once or files.

We probably also want to enforce that every torrent consist of a single file or folder. That would let us refactor the `name`, `path`, and `files` properties. Currently, when we want to delete data associated with a torrent, or implement Show In Finder, we have to resort to hacks.

@feross

**Comment by disarticulate** [comment]
- [ ] Apparent Memory Leaks:
    - https://github.com/webtorrent/webtorrent/issues/895#issuecomment-339510697
    - https://github.com/webtorrent/webtorrent/issues/1208
    - https://github.com/webtorrent/webtorrent/issues/1186
    - https://github.com/webtorrent/webtorrent/issues/1177

My trip through the source code didn't reveal to me where the issue is occuring, but it is definitely related to the pieceLength, which means the pieces aren't being GC'd or they're being duplicated.

**Comment by feross** [comment]
We're current at an insanely large minor version number — 0.99.4 — and we need to release 1.0.0 soon.

If we release another minor version – 0.100.0 — then the way that we calculate the version string in the wire protocol will roll over and cause problems. We only have two digits for the minor version!

**Comment by disarticulate** [comment]
what happens if you use the version number 💯

**Comment by feross** [comment]
The version part of the client ID will become `'00100'` which is a problem because it's supposed to only be 4 digits. For example, the current ID is `'0099'`.

**Comment by ultimate-tester** [comment]
So with the current version being v0.108.6, what is the up-to-date list on what's needed for a proper v1? I'd love to contribute.

**Comment by feross** [comment]
@ultimate-tester I'll close out this issue since it's super old and we can use the v1 milestone to track what we need to finish in order to release 1.0. https://github.com/webtorrent/webtorrent/milestone/1
